[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[functions]
  # Directory with serverless functions, including API routes
  directory = ".netlify/functions"
